// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-o1L9crZrI-IqR8S5jmMtMopJeDb98mk',
    appId: '1:551855096564:web:5535f773897f7ff22e54a1',
    messagingSenderId: '551855096564',
    projectId: 'madbox4195',
    authDomain: 'madbox4195.firebaseapp.com',
    databaseURL: 'https://madbox4195-default-rtdb.firebaseio.com',
    storageBucket: 'madbox4195.appspot.com',
    measurementId: 'G-W6SRD1Y8GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRpREPgQFv-d8oNhFBjg1efIx8JWRXRPQ',
    appId: '1:551855096564:android:b397c24f709a83d62e54a1',
    messagingSenderId: '551855096564',
    projectId: 'madbox4195',
    databaseURL: 'https://madbox4195-default-rtdb.firebaseio.com',
    storageBucket: 'madbox4195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBuR0P0QFze0TQR_MHXRvSUu2EeqxliI',
    appId: '1:551855096564:ios:f84be0cb990a33752e54a1',
    messagingSenderId: '551855096564',
    projectId: 'madbox4195',
    databaseURL: 'https://madbox4195-default-rtdb.firebaseio.com',
    storageBucket: 'madbox4195.appspot.com',
    iosBundleId: 'com.example.medapp',
  );
}
